<a href="https://colab.research.google.com/github/girlcrush95/basic-machine-learning/blob/main/%5BLesson1%5D_Basic_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
#Libraries for Deep Learning : Tensorflow and Pytorch
#Creating tensors - scalar, vector, matrix

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [3]:
#Tensors are fundamental building block of machine learning
#To represent data in a numerical way

#For example, a tensor shape [3, 224, 224] -> [colour_channels, hight, width],
# as image has 3 colour channels (RGB), a height of 224 pixels, and a width of 224 pixels.

In [7]:
#A scalar is a single number and in tensor-speak it's a zero dimension tensor.
# scalar - lower case leter

scalar = torch.tensor(5)
scalar

tensor(5)

In [8]:
# check the dimension - scalar has no dimension

scalar.ndim

0

In [9]:
# to get the tensor back as python int from scalar = torch.tensor(5)

scalar.item()

5

In [11]:
# vector - lower case letter

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
# check the ndim of vector

vector.ndim

1

In [26]:
#How many square brackets does vector have?
#which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

vector.shape

torch.Size([2])

In [72]:
#MATRIX - UPPER CASE LETTER

MATRIX = torch.tensor([[7,8],
                      [1,2],
                       [3,4]])
MATRIX

tensor([[7, 8],
        [1, 2],
        [3, 4]])

In [28]:
#Check Matrix dimension

MATRIX.ndim

2

In [29]:
# access the first index item in MATRIX, start from 0

MATRIX[0]

tensor([7, 8])

In [30]:
MATRIX[1]

tensor([1, 2])

In [73]:
MATRIX.shape

torch.Size([3, 2])

In [51]:
# TENSOR - UPPER CASE LETTER

TENSOR = torch.tensor([[[1,2,3],
                      [5,6,7],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 7],
         [7, 8, 9]]])

In [43]:
TENSOR.ndim

3

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])

In [53]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

In [56]:
TENSOR[0, 0]

tensor([1, 2, 3])

In [57]:
TENSOR[0,1]

tensor([5, 6, 7])

In [61]:
TENSOR[0,2]

tensor([7, 8, 9])

In [63]:
TENSOR[0,0,0]

tensor(1)

In [64]:
TENSOR[0,1,2]

tensor(7)

In [66]:
TENSOR[0,1,0]

tensor(5)

In [67]:
TENSOR[0,2,2]

tensor(9)

In [74]:
TENSOR[0,2,0]

tensor(7)